FROM nginx:latest

# Copy your Nginx configuration for Odoo
COPY /config/odoo-nginx.conf /etc/nginx/conf.d/

# Remove the default Nginx configuration
RUN rm /etc/nginx/conf.d/default.conf

# Copy SSL certificates into the container
COPY /ssl/localhost.crt /etc/nginx/ssl/
COPY /ssl/localhost.key /etc/nginx/ssl/

# Expose ports for HTTP and HTTPS
EXPOSE 80 443